"""Dynamic ICT model seeding utility.

This script intentionally deletes legacy hardcoded master models and replaces them
with models created through the ICT ModelFactory configuration flow.
"""

from __future__ import annotations

import json
from typing import Any

import db
from engine.ict_engine import ModelFactory

# Kept for compatibility with scripts/patch_model_rules.py
NAME_TO_TAG = {
    "bos": "bos",
    "mss": "mss",
    "choch": "choch",
    "fvg": "fvg",
    "ifvg": "ifvg",
    "liquidity sweep": "liquidity_sweep",
    "order block": "order_block",
    "breaker": "breaker",
}


def name_to_tag(name: str) -> str:
    k = str(name or "").strip().lower()
    if not k:
        return ""
    for label, tag in NAME_TO_TAG.items():
        if label in k:
            return tag
    return ""


def create_model(config: dict[str, Any]) -> dict[str, Any]:
    """Build a DB-ready model payload from dynamic ICT model config."""
    built = ModelFactory.create_model(config)
    max_score = sum(f.weight for f in built.features)
    rules = [
        {
            "id": f"{built.name.lower().replace(' ', '_')}_{i+1}",
            "name": f"{f.type} {f.tf}",
            "tag": name_to_tag(f.type),
            "weight": f.weight,
            "mandatory": False,
            "description": json.dumps({"type": f.type, "tf": f.tf, "direction": f.direction, "entry": f.entry}),
        }
        for i, f in enumerate(built.features)
    ]
    return {
        "id": built.name.upper().replace(" ", "_").replace("-", "_")[:50],
        "name": built.name,
        "pair": str(config.get("pair", "BTCUSDT")).upper(),
        "timeframe": str(config.get("timeframe", "5m")),
        "session": str(config.get("session", "Any")),
        "bias": str(config.get("bias", "Both")),
        "status": str(config.get("status", "inactive")),
        "rules": rules,
        "phase_timeframes": config.get("phase_timeframes", {"1": "4h", "2": "1h", "3": "15m", "4": "5m"}),
        "tier_a_threshold": max_score * 0.8,
        "tier_b_threshold": max_score * 0.65,
        "tier_c_threshold": max_score * 0.5,
        "rr_target": float(config.get("rr_target", 2.0)),
        "min_score": float(config.get("min_score", max_score * 0.5)),
        "description": str(config.get("description", "Dynamic ICT model generated by ModelFactory")),
    }


def purge_legacy_master_models() -> int:
    conn = db.acquire_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM models WHERE id LIKE 'MM_%' OR name ILIKE '%MASTER MODEL%'")
            deleted = int(cur.rowcount or 0)
        conn.commit()
        db._cache_clear("active_models")
        return deleted
    finally:
        db.release_conn(conn)


def seed_dynamic_models() -> list[str]:
    configs = [
        {
            "name": "BOS_Sweep_FVG_Model",
            "pair": "BTCUSDT",
            "timeframe": "5m",
            "features": [
                {"type": "BOS", "tf": "4h", "direction": "bullish", "weight": 2.0},
                {"type": "LiquiditySweep", "tf": "15m", "direction": "bullish", "weight": 1.0},
                {"type": "FVG", "tf": "5m", "entry": "CE", "direction": "bullish", "weight": 2.0},
            ],
            "min_score": 4,
            "max_time_delta": 180,
            "price_proximity_threshold": 0.3,
            "description": "HTF BOS + ITF sweep + LTF FVG CE continuation model.",
        }
    ]

    ids: list[str] = []
    for cfg in configs:
        payload = create_model(cfg)
        model_id = db.save_model(payload)
        ids.append(str(model_id))
    return ids


def run() -> None:
    deleted = purge_legacy_master_models()
    seeded = seed_dynamic_models()
    print(f"Deleted legacy master models: {deleted}")
    print(f"Seeded dynamic ICT models: {seeded}")


if __name__ == "__main__":
    run()
